### ISSUE TITLE
Can CLIPSeqTools process pair-end datasets?

### ISSUE THREAD

**Issue by LarryCKY** [mnsmar/clipseqtools#6]
Hi Maragkakis, 

Thank you for developing CLIPSeqTools. I have two FASTQ files (forward and reverse reads) for a biological sample. It seems that the pipeline only allows one fastq input. Can the tool analyze pair-end datasets? Thanks. 

Best,
Larry

**Comment by mnsmar** [comment]
Hi Larry, CLIPSeqTools cannot process paired-end datasets. It is relatively uncommon to have paired-end CLIP data thus we decided not to implement this feature. Given that CLIP binding sites are relatively short, the binding information is usually captured by the forward (or reverse) reads alone. Without knowing the details of your experiment, maybe you can try to analyze only one of your strands (forward or reverse).
